/* eslint-disable */

/// THIS IS GENERATED CODE.
/// DO NOT EDIT THIS FILE MANUALLY.

import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';

const getTranslations = (translate: TFunction) => {
  const translator = (key: string) => {
    return (options?: TOptions | string) => {
      return translate(key, options);
    };
  };

  return {
    demo: {
      title: translator('demo.title'),
      introduction: translator('demo.introduction')
    },
    forms: {
      chooseCountry: translator('forms.chooseCountry')
    }
  };
};

export const useTranslations = () => {
  const { t: translate } = useTranslation();
  const translations = useMemo(() => getTranslations(translate), [translate]);
  return translations;
};
